server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: gateway-server

  config:
    import: optional:file:.env[.properties]

  cloud:
    gateway:
      routes:
        # user-service
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/**
          filters:
            - StripPrefix=1
        - id: user-service-default
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - JwtFilter

        # video-service
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/video-service/**
          filters:
            - StripPrefix=1
            - JwtFilter

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: "Spring Cloud Gateway Global Filter"
            preLogger: true
            postLogger: true

jwt:
  secret: ${JWT_SECRET}